# Generated by Django 4.1 on 2024-03-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_consultant',
            name='ckd1',
            field=models.CharField(max_length=128, verbose_name='약관1'),
        ),
        migrations.AlterField(
            model_name='user_consultant',
            name='ckd2',
            field=models.CharField(max_length=128, verbose_name='약관2'),
        ),
        migrations.AlterField(
            model_name='user_consultant',
            name='ckd3',
            field=models.CharField(max_length=128, verbose_name='약관3'),
        ),
        migrations.AlterField(
            model_name='user_consultant',
            name='ckd4',
            field=models.CharField(max_length=128, verbose_name='약관4'),
        ),
        migrations.AlterField(
            model_name='user_consultant',
            name='ckd5',
            field=models.CharField(max_length=128, verbose_name='약관5'),
        ),
    ]
